[env:esp32dev]
platform = espressif32@6.3.2
board = esp32dev
board_build.flash_size = 2MB
framework = espidf

board_build.embed_files =
    src/object_pool/object_pool.iop

lib_deps =
    https://github.com/Open-Agriculture/AgIsoStack-plus-plus.git

build_flags =
    -I include
    -DCONFIG_ARDUHAL_LOG_DEFAULT_LEVEL=4
    -Wno-deprecated-declarations
    -Wno-error=cpp

monitor_speed = 115200

[env:esp32dev_debug]
platform = espressif32@6.3.2
board = esp32dev
board_build.flash_size = 2MB
framework = espidf

board_build.embed_files =
    src/object_pool/object_pool.iop

lib_deps =
    https://github.com/Open-Agriculture/AgIsoStack-plus-plus.git

build_flags =
    -I include
    -DCONFIG_ARDUHAL_LOG_DEFAULT_LEVEL=4
    -DDEBUG_ENABLED
    -Wno-deprecated-declarations
    -Wno-error=cpp

monitor_speed = 115200
